<?php

declare(strict_types=1);

namespace Xefreh\Judge0PhpClient\DTO;

readonly class Config
{
    public function __construct(
        public bool  $maintenanceMode,
        public bool  $enableWaitResult,
        public bool  $enableCompilerOptions,
        public array $allowedLanguagesForCompileOptions,
        public bool  $enableCommandLineArguments,
        public bool  $enableSubmissionDelete,
        public bool  $enableCallbacks,
        public int   $callbacksMaxTries,
        public float $callbacksTimeout,
        public bool  $enableAdditionalFiles,
        public int   $maxQueueSize,
        public float $cpuTimeLimit,
        public float $maxCpuTimeLimit,
        public float $cpuExtraTime,
        public float $maxCpuExtraTime,
        public float $wallTimeLimit,
        public float $maxWallTimeLimit,
        public int   $memoryLimit,
        public int   $maxMemoryLimit,
        public int   $stackLimit,
        public int   $maxStackLimit,
        public int   $maxProcessesAndOrThreads,
        public int   $maxMaxProcessesAndOrThreads,
        public bool  $enablePerProcessAndThreadTimeLimit,
        public bool  $allowEnablePerProcessAndThreadTimeLimit,
        public bool  $enablePerProcessAndThreadMemoryLimit,
        public bool  $allowEnablePerProcessAndThreadMemoryLimit,
        public int   $maxFileSize,
        public int   $maxMaxFileSize,
        public int   $numberOfRuns,
        public int   $maxNumberOfRuns,
        public bool  $redirectStderrToStdout,
        public int   $maxExtractSize,
        public bool  $enableBatchedSubmissions,
        public int   $maxSubmissionBatchSize,
        public float $submissionCacheDuration,
        public bool  $useDocsAsHomepage,
        public bool  $allowEnableNetwork,
        public bool  $enableNetwork,
    )
    {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            maintenanceMode: $data['maintenance_mode'],
            enableWaitResult: $data['enable_wait_result'],
            enableCompilerOptions: $data['enable_compiler_options'],
            allowedLanguagesForCompileOptions: $data['allowed_languages_for_compile_options'],
            enableCommandLineArguments: $data['enable_command_line_arguments'],
            enableSubmissionDelete: $data['enable_submission_delete'],
            enableCallbacks: $data['enable_callbacks'],
            callbacksMaxTries: $data['callbacks_max_tries'],
            callbacksTimeout: $data['callbacks_timeout'],
            enableAdditionalFiles: $data['enable_additional_files'],
            maxQueueSize: $data['max_queue_size'],
            cpuTimeLimit: $data['cpu_time_limit'],
            maxCpuTimeLimit: $data['max_cpu_time_limit'],
            cpuExtraTime: $data['cpu_extra_time'],
            maxCpuExtraTime: $data['max_cpu_extra_time'],
            wallTimeLimit: $data['wall_time_limit'],
            maxWallTimeLimit: $data['max_wall_time_limit'],
            memoryLimit: $data['memory_limit'],
            maxMemoryLimit: $data['max_memory_limit'],
            stackLimit: $data['stack_limit'],
            maxStackLimit: $data['max_stack_limit'],
            maxProcessesAndOrThreads: $data['max_processes_and_or_threads'],
            maxMaxProcessesAndOrThreads: $data['max_max_processes_and_or_threads'],
            enablePerProcessAndThreadTimeLimit: $data['enable_per_process_and_thread_time_limit'],
            allowEnablePerProcessAndThreadTimeLimit: $data['allow_enable_per_process_and_thread_time_limit'],
            enablePerProcessAndThreadMemoryLimit: $data['enable_per_process_and_thread_memory_limit'],
            allowEnablePerProcessAndThreadMemoryLimit: $data['allow_enable_per_process_and_thread_memory_limit'],
            maxFileSize: $data['max_file_size'],
            maxMaxFileSize: $data['max_max_file_size'],
            numberOfRuns: $data['number_of_runs'],
            maxNumberOfRuns: $data['max_number_of_runs'],
            redirectStderrToStdout: $data['redirect_stderr_to_stdout'],
            maxExtractSize: $data['max_extract_size'],
            enableBatchedSubmissions: $data['enable_batched_submissions'],
            maxSubmissionBatchSize: $data['max_submission_batch_size'],
            submissionCacheDuration: $data['submission_cache_duration'],
            useDocsAsHomepage: $data['use_docs_as_homepage'],
            allowEnableNetwork: $data['allow_enable_network'],
            enableNetwork: $data['enable_network'],
        );
    }

    public function toArray(): array
    {
        return [
            'maintenance_mode' => $this->maintenanceMode,
            'enable_wait_result' => $this->enableWaitResult,
            'enable_compiler_options' => $this->enableCompilerOptions,
            'allowed_languages_for_compile_options' => $this->allowedLanguagesForCompileOptions,
            'enable_command_line_arguments' => $this->enableCommandLineArguments,
            'enable_submission_delete' => $this->enableSubmissionDelete,
            'enable_callbacks' => $this->enableCallbacks,
            'callbacks_max_tries' => $this->callbacksMaxTries,
            'callbacks_timeout' => $this->callbacksTimeout,
            'enable_additional_files' => $this->enableAdditionalFiles,
            'max_queue_size' => $this->maxQueueSize,
            'cpu_time_limit' => $this->cpuTimeLimit,
            'max_cpu_time_limit' => $this->maxCpuTimeLimit,
            'cpu_extra_time' => $this->cpuExtraTime,
            'max_cpu_extra_time' => $this->maxCpuExtraTime,
            'wall_time_limit' => $this->wallTimeLimit,
            'max_wall_time_limit' => $this->maxWallTimeLimit,
            'memory_limit' => $this->memoryLimit,
            'max_memory_limit' => $this->maxMemoryLimit,
            'stack_limit' => $this->stackLimit,
            'max_stack_limit' => $this->maxStackLimit,
            'max_processes_and_or_threads' => $this->maxProcessesAndOrThreads,
            'max_max_processes_and_or_threads' => $this->maxMaxProcessesAndOrThreads,
            'enable_per_process_and_thread_time_limit' => $this->enablePerProcessAndThreadTimeLimit,
            'allow_enable_per_process_and_thread_time_limit' => $this->allowEnablePerProcessAndThreadTimeLimit,
            'enable_per_process_and_thread_memory_limit' => $this->enablePerProcessAndThreadMemoryLimit,
            'allow_enable_per_process_and_thread_memory_limit' => $this->allowEnablePerProcessAndThreadMemoryLimit,
            'max_file_size' => $this->maxFileSize,
            'max_max_file_size' => $this->maxMaxFileSize,
            'number_of_runs' => $this->numberOfRuns,
            'max_number_of_runs' => $this->maxNumberOfRuns,
            'redirect_stderr_to_stdout' => $this->redirectStderrToStdout,
            'max_extract_size' => $this->maxExtractSize,
            'enable_batched_submissions' => $this->enableBatchedSubmissions,
            'max_submission_batch_size' => $this->maxSubmissionBatchSize,
            'submission_cache_duration' => $this->submissionCacheDuration,
            'use_docs_as_homepage' => $this->useDocsAsHomepage,
            'allow_enable_network' => $this->allowEnableNetwork,
            'enable_network' => $this->enableNetwork,
        ];
    }
}
